// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5VSOaGY8RHjzAUu1y076C36Mu7-Xb0g',
    appId: '1:618243697542:web:0a7645788cbc3e247a5a07',
    messagingSenderId: '618243697542',
    projectId: 'pet-fit-884a6',
    authDomain: 'pet-fit-884a6.firebaseapp.com',
    storageBucket: 'pet-fit-884a6.appspot.com',
    measurementId: 'G-Y12VR5ST5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEfpYrIWKpfKjDsQ2FkRps_uN_6KMX6tU',
    appId: '1:618243697542:android:d8e5434657c5ed087a5a07',
    messagingSenderId: '618243697542',
    projectId: 'pet-fit-884a6',
    storageBucket: 'pet-fit-884a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR17KEVRhcYGqTlNp8U9WPYAgfdgwugF4',
    appId: '1:618243697542:ios:bb57ec3e6c368f4b7a5a07',
    messagingSenderId: '618243697542',
    projectId: 'pet-fit-884a6',
    storageBucket: 'pet-fit-884a6.appspot.com',
    iosBundleId: 'com.example.petFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR17KEVRhcYGqTlNp8U9WPYAgfdgwugF4',
    appId: '1:618243697542:ios:07e38e2787ecd6607a5a07',
    messagingSenderId: '618243697542',
    projectId: 'pet-fit-884a6',
    storageBucket: 'pet-fit-884a6.appspot.com',
    iosBundleId: 'com.example.petFit.RunnerTests',
  );
}
